theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.4.24
  download_url: https://github.com/chrisant996/clink/releases/download/v1.4.24/clink.1.4.24.688975.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.4.24/clink.1.4.24.688975_setup.exe
