theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.4.16
  download_url: https://github.com/chrisant996/clink/releases/download/v1.4.16/clink.1.4.16.b8efc4.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.4.16/clink.1.4.16.b8efc4_setup.exe
