theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.4.0
  download_url: https://github.com/chrisant996/clink/releases/download/v1.4.0/clink.1.4.0.74a8d2.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.4.0/clink.1.4.0.74a8d2_setup.exe
