theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.4.2
  download_url: https://github.com/chrisant996/clink/releases/download/v1.4.2/clink.1.4.2.e8df54.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.4.2/clink.1.4.2.e8df54_setup.exe
