theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.3.45
  download_url: https://github.com/chrisant996/clink/releases/download/v1.3.45/clink.1.3.45.83a752.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.3.45/clink.1.3.45.83a752_setup.exe
