theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.3.33
  download_url: https://github.com/chrisant996/clink/releases/download/v1.3.33/clink.1.3.33.f2cac3.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.3.33/clink.1.3.33.f2cac3_setup.exe
