theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.4.17
  download_url: https://github.com/chrisant996/clink/releases/download/v1.4.17/clink.1.4.17.04fa7b.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.4.17/clink.1.4.17.04fa7b_setup.exe
