theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.3.32
  download_url: https://github.com/chrisant996/clink/releases/download/v1.3.32/clink.1.3.32.52f559.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.3.32/clink.1.3.32.52f559_setup.exe
