theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.3.26
  download_url: https://github.com/chrisant996/clink/releases/download/v1.3.26/clink.1.3.26.eec90c.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.3.26/clink.1.3.26.eec90c_setup.exe
