theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.3.38
  download_url: https://github.com/chrisant996/clink/releases/download/v1.3.38/clink.1.3.38.d767b9.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.3.38/clink.1.3.38.d767b9_setup.exe
