theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.3.22
  download_url: https://github.com/chrisant996/clink/releases/download/v1.3.22/clink.1.3.22.0d2d97.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.3.22/clink.1.3.22.0d2d97_setup.exe
