theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.3.50
  download_url: https://github.com/chrisant996/clink/releases/download/v1.3.50/clink.1.3.50.c98f5f.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.3.50/clink.1.3.50.c98f5f_setup.exe
