theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.4.8
  download_url: https://github.com/chrisant996/clink/releases/download/v1.4.8/clink.1.4.8.dbc12c.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.4.8/clink.1.4.8.dbc12c_setup.exe
