theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.3.44
  download_url: https://github.com/chrisant996/clink/releases/download/v1.3.44/clink.1.3.44.2eb456.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.3.44/clink.1.3.44.2eb456_setup.exe
