theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.4.9
  download_url: https://github.com/chrisant996/clink/releases/download/v1.4.9/clink.1.4.9.fc640f.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.4.9/clink.1.4.9.fc640f_setup.exe
