theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.4.13
  download_url: https://github.com/chrisant996/clink/releases/download/v1.4.13/clink.1.4.13.0066c6.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.4.13/clink.1.4.13.0066c6_setup.exe
