theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.4.10
  download_url: https://github.com/chrisant996/clink/releases/download/v1.4.10/clink.1.4.10.45c041.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.4.10/clink.1.4.10.45c041_setup.exe
