theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.4.26
  download_url: https://github.com/chrisant996/clink/releases/download/v1.4.26/clink.1.4.26.4fe328.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.4.26/clink.1.4.26.4fe328_setup.exe
