theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.4.25
  download_url: https://github.com/chrisant996/clink/releases/download/v1.4.25/clink.1.4.25.e0d48c.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.4.25/clink.1.4.25.e0d48c_setup.exe
