theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.4.7
  download_url: https://github.com/chrisant996/clink/releases/download/v1.4.7/clink.1.4.7.524e49.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.4.7/clink.1.4.7.524e49_setup.exe
