theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.3.29
  download_url: https://github.com/chrisant996/clink/releases/download/v1.3.29/clink.1.3.29.b68f6d.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.3.29/clink.1.3.29.b68f6d_setup.exe
