theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.3.23
  download_url: https://github.com/chrisant996/clink/releases/download/v1.3.23/clink.1.3.23.5d5aed.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.3.23/clink.1.3.23.5d5aed_setup.exe
