theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.4.28
  download_url: https://github.com/chrisant996/clink/releases/download/v1.4.28/clink.1.4.28.b0080b.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.4.28/clink.1.4.28.b0080b_setup.exe
