theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.3.24
  download_url: https://github.com/chrisant996/clink/releases/download/v1.3.24/clink.1.3.24.a8a0d2.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.3.24/clink.1.3.24.a8a0d2_setup.exe
