theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.4.19
  download_url: https://github.com/chrisant996/clink/releases/download/v1.4.19/clink.1.4.19.57e404.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.4.19/clink.1.4.19.57e404_setup.exe
