theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.3.37
  download_url: https://github.com/chrisant996/clink/releases/download/v1.3.37/clink.1.3.37.b85068.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.3.37/clink.1.3.37.b85068_setup.exe
