theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.3.47
  download_url: https://github.com/chrisant996/clink/releases/download/v1.3.47/clink.1.3.47.d5796b.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.3.47/clink.1.3.47.d5796b_setup.exe
