theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.3.51
  download_url: https://github.com/chrisant996/clink/releases/download/v1.3.51/clink.1.3.51.28dd7d.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.3.51/clink.1.3.51.28dd7d_setup.exe
