theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.4.18
  download_url: https://github.com/chrisant996/clink/releases/download/v1.4.18/clink.1.4.18.792517.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.4.18/clink.1.4.18.792517_setup.exe
