theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.4.4
  download_url: https://github.com/chrisant996/clink/releases/download/v1.4.4/clink.1.4.4.7fe1ca.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.4.4/clink.1.4.4.7fe1ca_setup.exe
