theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.3.48
  download_url: https://github.com/chrisant996/clink/releases/download/v1.3.48/clink.1.3.48.4dadd8.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.3.48/clink.1.3.48.4dadd8_setup.exe
