theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.3.49
  download_url: https://github.com/chrisant996/clink/releases/download/v1.3.49/clink.1.3.49.3b3066.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.3.49/clink.1.3.49.3b3066_setup.exe
